#!/usr/bin/env python3
"""State-based core for caddy/generate-caddyfile.sh.

Keeps desired subdomains in state.json (the source of truth) and renders
Caddyfile.local as pure derived output. Stdlib only.

Commands: sync (interactive merge of discovered guests into state),
render (pure Caddyfile on stdout). Prompts and logs go to stderr.
"""

import argparse
import json
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

STATE_VERSION = 1
GENERATED_HEADER = (
    "# Generated by caddy/generate-caddyfile.sh — do not edit.\n"
    "# Source of truth: caddy/state.json\n"
)

__all__ = [
    "Guest",
    "STATE_VERSION",
    "empty_state",
    "load_state",
    "save_state",
    "services_for_ip",
    "suggest_subdomain",
    "default_tls_for",
    "suggest_port",
    "sanitize_subdomain",
    "prompt_tls",
    "merge_guests",
    "render_block",
    "render_state",
    "read_prompt",
    "main",
]


@dataclass
class Guest:
    name: str
    gid: str
    gtype: str
    ip: str
    ports: List[int] = field(default_factory=list)


def empty_state(domain: str) -> Dict[str, Any]:
    return {"version": STATE_VERSION, "domain": domain, "entries": {}}


def load_state(path: str) -> Dict[str, Any]:
    with open(path, encoding="utf-8") as handle:
        state = json.load(handle)
    if (
        not isinstance(state, dict)
        or state.get("version") != STATE_VERSION
        or not isinstance(state.get("entries"), dict)
    ):
        raise ValueError("unsupported state file: %s" % path)
    return state


def save_state(state: Dict[str, Any], path: str) -> None:
    directory = os.path.dirname(os.path.abspath(path))
    descriptor, tmp_path = tempfile.mkstemp(
        dir=directory, prefix=".state.", suffix=".json"
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(state, handle, indent=2, sort_keys=True)
            handle.write("\n")
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def services_for_ip(
    entries: Dict[str, Dict[str, Any]],
    wanted_ip: str,
    exclude: str,
    claimed: Set[str],
) -> List[str]:
    return [
        name
        for name, entry in entries.items()
        if name
        and name != exclude
        and name not in claimed
        and entry.get("source", "auto") == "auto"
        and entry.get("ip") == wanted_ip
    ]


def suggest_subdomain(
    entries: Dict[str, Dict[str, Any]], wanted_port: int, claimed: Set[str]
) -> Optional[str]:
    matches = [
        name
        for name, entry in entries.items()
        if name and name not in claimed and entry.get("port") == wanted_port
    ]
    if len(matches) == 1:
        return matches[0]
    return None


def default_tls_for(name: str) -> str:
    if name.startswith("nextcloud"):
        return "https"
    return "http"


def suggest_port(ports: List[int]) -> int:
    if 80 in ports:
        return 80
    if 443 in ports:
        return 443
    if ports:
        return ports[0]
    return 80


def sanitize_subdomain(raw: str) -> str:
    return "".join(raw.split()).split(".", 1)[0]


def prompt_tls(
    name: str,
    current: Optional[str],
    domain: str,
    ask: Callable[[str], str],
    log: Callable[[str], None],
) -> str:
    if current in ("http", "https"):
        label = "HTTPS (tls internal)" if current == "https" else "HTTP"
        log("  \u2713 %s \u2192 saved TLS: %s" % (name, label))
        return current
    default = default_tls_for(name)
    marker = "Y" if default == "https" else "n"
    choice = ask(
        "  HTTPS (tls internal) for %s.%s? [Y/n] (default: %s): "
        % (name, domain, marker)
    ).strip().lower()
    if choice in ("y", "yes"):
        return "https"
    if choice in ("n", "no"):
        return "http"
    return default


def merge_guests(
    guests: List[Guest],
    state: Dict[str, Any],
    domain: str,
    ask: Callable[[str], str],
    log: Callable[[str], None],
) -> Set[str]:
    entries = state["entries"]
    claimed: Set[str] = set()
    touched: Set[str] = set()

    def set_entry(
        name: str, ip: str, port: int, tls: str, guest: Optional[str]
    ) -> None:
        entry = entries.get(name)
        if entry is None:
            entry = {"source": "auto"}
            entries[name] = entry
        entry["ip"] = ip
        entry["port"] = port
        entry["tls"] = tls
        entry["guest"] = guest

    def reuse_known(name: str, ip: str) -> None:
        entry = entries[name]
        log("  \u2713 %s \u2192 saved port %d" % (name, entry["port"]))
        set_entry(name, ip, entry["port"], entry["tls"], name)
        prompt_tls(name, entry["tls"], domain, ask, log)
        claimed.add(name)
        touched.add(name)

    for guest in guests:
        name = guest.name
        ip = guest.ip
        if name in entries and entries[name].get("guest") == name:
            reuse_known(name, ip)
            continue
        reattach = services_for_ip(entries, ip, name, claimed)
        if reattach:
            log("  \u2713 %s \u2192 saved multi-service:" % name)
            for svc in reattach:
                log(
                    "    \u2713 %s.%s \u2192 %s:%d"
                    % (svc, domain, ip, entries[svc]["port"])
                )
                set_entry(svc, ip, entries[svc]["port"], entries[svc]["tls"], name)
                prompt_tls(svc, entries[svc].get("tls"), domain, ask, log)
                claimed.add(svc)
                touched.add(svc)
            if name in entries:
                reuse_known(name, ip)
            continue
        if name in entries:
            reuse_known(name, ip)
            continue
        ports = list(guest.ports)
        multi = False
        if len(ports) > 1:
            answer = ask(
                "  Does %s host multiple services (one subdomain per port)? [y/N]: "
                % name
            ).strip().lower()
            multi = answer in ("y", "yes")
        if multi:
            added_here: List[str] = []
            for port in ports:
                suggestion = suggest_subdomain(entries, port, claimed)
                if suggestion:
                    raw = ask(
                        "  Subdomain for %s port %d (%s) [default: %s]: "
                        % (name, port, ip, suggestion)
                    )
                    raw = raw.strip() or suggestion
                else:
                    raw = ask(
                        "  Subdomain for %s port %d (%s) [empty to skip]: "
                        % (name, port, ip)
                    )
                svc = sanitize_subdomain(raw)
                if not svc:
                    continue
                tls = prompt_tls(
                    svc, entries[svc].get("tls") if svc in entries else None,
                    domain, ask, log,
                )
                set_entry(svc, ip, port, tls, name)
                claimed.add(svc)
                touched.add(svc)
                added_here.append(svc)
                log("  \u2713 %s.%s \u2192 %s:%d" % (svc, domain, ip, port))
            if not added_here:
                log(
                    "  No subdomain given for %s \u2014 falling back to single-service"
                    % name
                )
            else:
                continue
        suggested = suggest_port(ports)
        raw_port = ask(
            "  Port for %s.%s (%s) [default: %d]: " % (name, domain, ip, suggested)
        ).strip() or str(suggested)
        if re.match(r"^[0-9]+$", raw_port) and 1 <= int(raw_port) <= 65535:
            port = int(raw_port)
        else:
            log("  Invalid port '%s' \u2014 using %d" % (raw_port, suggested))
            port = suggested
        tls = prompt_tls(
            name, entries[name].get("tls") if name in entries else None,
            domain, ask, log,
        )
        set_entry(name, ip, port, tls, name)
        claimed.add(name)
        touched.add(name)
    return touched


def render_block(name: str, ip: str, port: int, tls_mode: str, domain: str) -> str:
    if tls_mode == "https":
        return "%s.%s {\n    tls internal\n    reverse_proxy %s:%d\n}\n\n" % (
            name,
            domain,
            ip,
            port,
        )
    return "http://%s.%s {\n    reverse_proxy %s:%d\n}\n\n" % (name, domain, ip, port)


def render_state(
    state: Dict[str, Any], domain: str, touched: Set[str]
) -> Tuple[str, List[str]]:
    parts = [GENERATED_HEADER, "\n"]
    warnings = []
    for name, entry in state["entries"].items():
        if not name:
            continue
        parts.append(
            render_block(name, entry["ip"], entry["port"], entry["tls"], domain)
        )
        if name not in touched:
            warnings.append(
                "  Preserving unmanaged block %s.%s (%s:%d)"
                % (name, domain, entry["ip"], entry["port"])
            )
    return "".join(parts), warnings


def read_prompt(prompt: str) -> str:
    print(prompt, end="", file=sys.stderr, flush=True)
    try:
        return input()
    except EOFError:
        return ""


def load_guests(path: str) -> List[Guest]:
    with open(path, encoding="utf-8") as handle:
        raw_guests = json.load(handle)
    return [
        Guest(
            name=item["name"],
            gid=str(item.get("gid", "")),
            gtype=str(item.get("gtype", "ct")),
            ip=item["ip"],
            ports=[int(port) for port in item.get("ports", [])],
        )
        for item in raw_guests
    ]


def cmd_sync(args: argparse.Namespace) -> int:
    def log(line: str) -> None:
        print(line, file=sys.stderr)

    try:
        guests = load_guests(args.guests_file)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print("Error: cannot load guests file: %s" % (exc,), file=sys.stderr)
        return 1
    try:
        state = load_state(args.state)
    except FileNotFoundError:
        state = empty_state(args.domain)
    except (OSError, ValueError) as exc:
        print("Error: cannot load state file: %s" % (exc,), file=sys.stderr)
        return 1
    if state["entries"]:
        log(
            "  Found %d saved entr%s"
            % (len(state["entries"]), "y" if len(state["entries"]) == 1 else "ies")
        )
    touched = merge_guests(guests, state, args.domain, read_prompt, log)
    state["domain"] = args.domain
    _, warnings = render_state(state, args.domain, touched)
    for warning in warnings:
        log(warning)
    try:
        save_state(state, args.state)
    except OSError as exc:
        print("Error: cannot save state file: %s" % (exc,), file=sys.stderr)
        return 1
    return 0


def cmd_render(args: argparse.Namespace) -> int:
    try:
        state = load_state(args.state)
    except (OSError, ValueError) as exc:
        print("Error: cannot load state file: %s" % (exc,), file=sys.stderr)
        return 1
    domain = state.get("domain") or "marx.home"
    text, _ = render_state(state, domain, set(state["entries"]))
    sys.stdout.write(text)
    return 0


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Caddyfile state database.")
    sub = parser.add_subparsers(dest="command", required=True)
    sync_parser = sub.add_parser("sync", help="merge guests into state")
    sync_parser.add_argument("--domain", required=True)
    sync_parser.add_argument("--state", required=True)
    sync_parser.add_argument("--guests-file", required=True)
    sync_parser.set_defaults(func=cmd_sync)
    render_parser = sub.add_parser("render", help="render Caddyfile")
    render_parser.add_argument("--state", required=True)
    render_parser.set_defaults(func=cmd_render)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
